name = "granada"
type = "webpack"
account_id = '0d13146e53ce108313d59c78906cd900'
usage_model = ''
compatibility_flags = []
site = {bucket = "./build",entry-point = "workers-site"}
compatibility_date = "2022-02-09"
workers_dev = false
zone_id = 'e6bf1f06148cb143e391370e9edf3aef'
route = 'https://granada.ulysseskee.software/*'